### MIDTERM LINEAR ALGEBRA A (DM 4209) <br />Wednesday, April 5th,2017 8:30 - 13:30 | Lecturer: Iwan Njoto Sandjaja
###### Problem 1. (10): Can three vectors in the $xy$ plane have $u.v < 0$ and $u.w < 0$ and $v.w< 0$? What it means geometrically? If yes it can, give example!

###### Problem 2. (20): Start with the vector $u_0 = (1, 0)$. Multiply again and again by the same “Markov matrix” $A = [.8$ $.3$; $.2$ $.7]$. The next three vectors are $u_1$, $u_2$, $u_3$:

$$
\begin{align}
 u_1 = \begin{bmatrix}{.8} & {.3} \\ {.2} & {.7} \end{bmatrix} \begin{bmatrix}1\\ 0 \end{bmatrix} = \begin{bmatrix}{.8}\\ {.2} \end{bmatrix}\text{, } & u_2 = Au_1 = \text{______, } & u_3 = Au_2 = \text{______.}
\end{align} 
$$

What property do you notice for all four vectors $u_0$, $u_1$, $u_2$, $u_3$?

In [2]:
import numpy as np
u1 = np.array([[.8,.3],[.2,.7]])
print(u1)

[[ 0.8  0.3]
 [ 0.2  0.7]]


In [5]:
v = np.array([[1.0],[0.0]])
print(v)

[[ 1.]
 [ 0.]]


In [6]:
r=u1.dot(v)
print(r)

[[ 0.8]
 [ 0.2]]


In [7]:
r1 = u1.dot(r)
print(r1)

[[ 0.7]
 [ 0.3]]


In [10]:
r2 = u1.dot(r1)
print(r2)

[[ 0.65]
 [ 0.35]]


###### Problem 3. (20): Find the triangular matrix $E$ that reduces “Pascal’s matrix” to a smaller Pascal:
$$
 E \  \begin{bmatrix}1 & 0 & 0 & 0 \\ 1 & 1 & 0 & 0 \\ 1 & 2 & 1 & 0 \\ 1 & 3 & 3 & 1 \end{bmatrix} = \begin{bmatrix}1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 1 & 1 & 0 \\ 0 & 1 & 2 & 1 \end{bmatrix} .
$$

Which matrix $M$ (multiplying several $E$’s) reduces Pascal all the way to $I$?

###### Problem 4. (10): Suppose $A$ is $m$ by $n$, $B$ is $n$ by $p$, and $C$ is $p$ by $q$. Then the multiplication count for $(AB)C$ is $mnp$ + $mpq$. The multiplication count from $A$ times $BC$ with $mnq$ + $npq$ separate multiplications.

- If $A$ is 2 by 4, $B$ is 4 by 7, and $C$ is 7 by 10, do you prefer $(AB)C$ or $A(BC)$?
- With $N$-component vectors, would you choose $(u^T v)w^T$ or $u^T (vw^T )$?
- Divide by $mnpq$ to show that $(AB)C$ is faster when $n^{-1} + q^{−1} < m^{−1} + p^{−1}$.


###### Problem 5. (30): Find $A^{-1}, B^{-1}$ and $C^{-1}$  for:

$$
\begin{align}
 A =\begin{bmatrix}1 & a & b \\ 0 & 1 & c \\ 0 & 0 & 1 \end{bmatrix}, 
 B = \begin{bmatrix}a & b & c \\ d & e & f \\ g & h & i \end{bmatrix},  
 C = \begin{bmatrix}1 & -a & 0 & 0 \\ 0 & 1 & -b & 0 \\ 0 & 0 & 1 & -c \\ 0 & 0 & 0 & 1\end{bmatrix}. 
 \end{align}
$$


###### Problem 6. (20) Permutation Matrix 
(a) Find a 3 by 3 permutation matrix with $P^3 = I$ (but not $P = I$). <br/>(b) Find a 4 by 4 permutation $\widehat{P}$ with $\widehat{P}^4 \neq I$.